/*
 * watch this video on forms: https://www.youtube.com/watch?v=KxzVF--FtUY
 */
package forms;

import beans.Ingredient;
import beans.Recipe;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilities.Calculate;
import static utilities.Calculate.nutrientTotal;
import utilities.FileManagement;

/**
 *
 * @author Tender
 */
public class MainWindow extends javax.swing.JFrame {

    static DefaultTableModel table;
    static Recipe recipe;
    // totals for final display label in NutritionLabel
    Ingredient ingredientRunningTotals;
    Ingredient selectedIngredient;
    String selectedMeasurement;
    double calorieRunningTotals;
    double fatRunningTotals;
    double cholRunningTotals;
    double sodiumRunningTotals;
    double carbRunningTotals;
    double fiberRunningTotals;
    double proteinRunningTotals;    
    
    /**
     * Creates new form MainWindow
     */    
    public MainWindow() {
        initComponents();
        table=(DefaultTableModel)jTable.getModel();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelIngredients = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jBtnEditIngred = new javax.swing.JButton();
        jButtonDeleteIngredient = new javax.swing.JButton();
        jBtnAddIngredient = new javax.swing.JButton();
        jBtnAddIngredient1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanelDirections = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDirections = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanelRecipe = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtfRecipeName = new javax.swing.JTextField();
        jBtnGetLabel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfCookTemp = new javax.swing.JTextField();
        jtfCookTime = new javax.swing.JTextField();
        jBtnClose = new javax.swing.JButton();
        jtfWeight = new javax.swing.JTextField();
        jBtnResetAll = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jtfServings = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        iName = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        iServingSize = new javax.swing.JTextField();
        iCalories = new javax.swing.JTextField();
        iFat = new javax.swing.JTextField();
        iCarbs = new javax.swing.JTextField();
        iFiber = new javax.swing.JTextField();
        iProtein = new javax.swing.JTextField();
        iAmtInRecipe = new javax.swing.JTextField();
        iMeasurement = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        iCholesterol = new javax.swing.JTextField();
        iSodium = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jButtonAddIngredient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nutrition Label Creator");

        jLabel4.setFont(new java.awt.Font("Calibri Light", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(137, 137, 137))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30))
        );

        jPanelIngredients.setBackground(new java.awt.Color(51, 51, 51));

        jTable.setBackground(new java.awt.Color(240, 247, 212));
        jTable.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jTable.setForeground(new java.awt.Color(52, 123, 152));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Amount", "Measure", "Ingredient", "Serving Size", "Calories", "Fat", "Cholesterol", "Sodium", "Carbohydrates", "Fiber", "Protein"
            }
        ));
        jTable.setToolTipText("");
        jTable.setGridColor(new java.awt.Color(52, 123, 152));
        jTable.setRowHeight(20);
        jTable.setRowMargin(3);
        jTable.setSelectionBackground(new java.awt.Color(102, 176, 50));
        jTable.setSelectionForeground(new java.awt.Color(240, 247, 212));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable);

        jBtnEditIngred.setBackground(new java.awt.Color(102, 176, 50));
        jBtnEditIngred.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jBtnEditIngred.setForeground(new java.awt.Color(9, 40, 52));
        jBtnEditIngred.setText("Edit");
        jBtnEditIngred.setBorderPainted(false);
        jBtnEditIngred.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnEditIngredMouseClicked(evt);
            }
        });
        jBtnEditIngred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditIngredActionPerformed(evt);
            }
        });

        jButtonDeleteIngredient.setBackground(new java.awt.Color(102, 176, 50));
        jButtonDeleteIngredient.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButtonDeleteIngredient.setForeground(new java.awt.Color(9, 40, 52));
        jButtonDeleteIngredient.setText("Delete");
        jButtonDeleteIngredient.setBorderPainted(false);
        jButtonDeleteIngredient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDeleteIngredientMouseClicked(evt);
            }
        });
        jButtonDeleteIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteIngredientActionPerformed(evt);
            }
        });

        jBtnAddIngredient.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jBtnAddIngredient.setForeground(new java.awt.Color(9, 40, 52));
        jBtnAddIngredient.setText("Add Ingredient");
        jBtnAddIngredient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAddIngredientMouseClicked(evt);
            }
        });
        jBtnAddIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddIngredientActionPerformed(evt);
            }
        });

        jBtnAddIngredient1.setBackground(new java.awt.Color(102, 176, 50));
        jBtnAddIngredient1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jBtnAddIngredient1.setForeground(new java.awt.Color(9, 40, 52));
        jBtnAddIngredient1.setText("Search");
        jBtnAddIngredient1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAddIngredient1MouseClicked(evt);
            }
        });
        jBtnAddIngredient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddIngredient1ActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(240, 247, 212));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanelIngredientsLayout = new javax.swing.GroupLayout(jPanelIngredients);
        jPanelIngredients.setLayout(jPanelIngredientsLayout);
        jPanelIngredientsLayout.setHorizontalGroup(
            jPanelIngredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIngredientsLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanelIngredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelIngredientsLayout.createSequentialGroup()
                        .addComponent(jBtnAddIngredient)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnEditIngred)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeleteIngredient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnAddIngredient1)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanelIngredientsLayout.setVerticalGroup(
            jPanelIngredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIngredientsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelIngredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnEditIngred)
                    .addComponent(jButtonDeleteIngredient)
                    .addComponent(jBtnAddIngredient)
                    .addComponent(jBtnAddIngredient1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanelDirections.setBackground(new java.awt.Color(51, 51, 51));

        jtaDirections.setBackground(new java.awt.Color(240, 247, 212));
        jtaDirections.setColumns(20);
        jtaDirections.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jtaDirections.setForeground(new java.awt.Color(52, 123, 152));
        jtaDirections.setLineWrap(true);
        jtaDirections.setRows(5);
        jScrollPane1.setViewportView(jtaDirections);

        jLabel2.setBackground(new java.awt.Color(240, 247, 212));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Cooking Directions");

        javax.swing.GroupLayout jPanelDirectionsLayout = new javax.swing.GroupLayout(jPanelDirections);
        jPanelDirections.setLayout(jPanelDirectionsLayout);
        jPanelDirectionsLayout.setHorizontalGroup(
            jPanelDirectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDirectionsLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelDirectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDirectionsLayout.setVerticalGroup(
            jPanelDirectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDirectionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelRecipe.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(178, 215, 50));
        jLabel3.setText("Recipe Name");

        jtfRecipeName.setBackground(new java.awt.Color(240, 247, 212));
        jtfRecipeName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jBtnGetLabel.setBackground(new java.awt.Color(102, 176, 50));
        jBtnGetLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jBtnGetLabel.setForeground(new java.awt.Color(9, 40, 52));
        jBtnGetLabel.setText("Get Nutrition Label");
        jBtnGetLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnGetLabelMouseClicked(evt);
            }
        });
        jBtnGetLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGetLabelActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(178, 215, 50));
        jLabel6.setText("Cook/Setting Temperature");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(178, 215, 50));
        jLabel7.setText("Weight after Cooking in Grams");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(178, 215, 50));
        jLabel8.setText("Cook/Setting Time");

        jtfCookTemp.setBackground(new java.awt.Color(240, 247, 212));
        jtfCookTemp.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jtfCookTime.setBackground(new java.awt.Color(240, 247, 212));
        jtfCookTime.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jBtnClose.setBackground(new java.awt.Color(102, 176, 50));
        jBtnClose.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jBtnClose.setForeground(new java.awt.Color(9, 40, 52));
        jBtnClose.setText("Quit");
        jBtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCloseActionPerformed(evt);
            }
        });

        jtfWeight.setBackground(new java.awt.Color(240, 247, 212));
        jtfWeight.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jBtnResetAll.setBackground(new java.awt.Color(102, 176, 50));
        jBtnResetAll.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jBtnResetAll.setForeground(new java.awt.Color(9, 40, 52));
        jBtnResetAll.setText("Reset All");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(178, 215, 50));
        jLabel9.setText("Number of Servings");

        jtfServings.setBackground(new java.awt.Color(240, 247, 212));
        jtfServings.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanelRecipeLayout = new javax.swing.GroupLayout(jPanelRecipe);
        jPanelRecipe.setLayout(jPanelRecipeLayout);
        jPanelRecipeLayout.setHorizontalGroup(
            jPanelRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRecipeLayout.createSequentialGroup()
                .addGroup(jPanelRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRecipeLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanelRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRecipeLayout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jtfRecipeName, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRecipeLayout.createSequentialGroup()
                                .addGroup(jPanelRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelRecipeLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtfServings))
                                    .addGroup(jPanelRecipeLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfCookTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34)
                                .addGroup(jPanelRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelRecipeLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelRecipeLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfCookTime, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanelRecipeLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jBtnResetAll, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnGetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRecipeLayout.setVerticalGroup(
            jPanelRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRecipeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfRecipeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanelRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jtfServings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfCookTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jtfCookTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanelRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnResetAll, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel31.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        jLabel31.setText("Nutrition Label");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel32.setText("Serving Size in grams");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel33.setText("Calories");

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel34.setText("Carbohydrates");

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel35.setText("Total Fat");

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel36.setText("Dietary Fiber");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel37.setText("Ingredient Name");

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel38.setText("Amount In Recipe");

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel39.setText("Protein");

        iName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));

        iServingSize.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        iCalories.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        iFat.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        iCarbs.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        iFiber.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        iProtein.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        iAmtInRecipe.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        iMeasurement.setBackground(new java.awt.Color(51, 51, 51));
        iMeasurement.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        iMeasurement.setForeground(new java.awt.Color(255, 255, 255));
        iMeasurement.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "grams", "liquid oz", "dry oz", "teaspoon", "tablespoon", "milligram", "liquid cup", "dry cup", "liquid pint", "dry pint" }));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel40.setText("Cholesterol");

        iCholesterol.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        iSodium.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel41.setText("Sodium");

        jButtonAddIngredient.setText("Add Ingredient to Recipe");
        jButtonAddIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddIngredientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(iCarbs, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(iCholesterol, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(iFat, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(iSodium, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel37)
                            .addComponent(iName)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(iFiber, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(iProtein)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(iMeasurement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel38)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(iAmtInRecipe, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(iCalories)
                                    .addComponent(iServingSize)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAddIngredient)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(iServingSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(iCalories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(iFat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(iCholesterol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(iSodium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(iCarbs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(iFiber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(iProtein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(iAmtInRecipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iMeasurement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAddIngredient)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelDirections, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelIngredients, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelRecipe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelIngredients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelDirections, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRecipe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // DELETE THIS MOUSE CLICK EVENT (Use action performed)
    private void jBtnEditIngredMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEditIngredMouseClicked
// change this to "action performed"        
        // see video link at the top of page for this (last half of video)
    }//GEN-LAST:event_jBtnEditIngredMouseClicked
    // DELETE THIS MOUSE CLICK EVENT (Use action performed)
    private void jButtonDeleteIngredientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteIngredientMouseClicked
// change this to "action performed"        
        // see video link at the top of page for this (last 2 minutes of video)
    }//GEN-LAST:event_jButtonDeleteIngredientMouseClicked
    // DELETE THIS MOUSE CLICK EVENT (Used jBtnAddIngredientActionPerformed instead
    private void jBtnAddIngredientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAddIngredientMouseClicked
      // dont think i need this anymore      
      System.out.println("Btn: add ingredient :::: mouse clicked  ::::::");
    }//GEN-LAST:event_jBtnAddIngredientMouseClicked
    // get the value in the table (for each nutrient) and save to selectedIngredient() object
    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        String amount = String.valueOf(table.getValueAt(jTable.getSelectedRow(), 0));   
        selectedMeasurement = String.valueOf(table.getValueAt(jTable.getSelectedRow(), 1));            
        String name = String.valueOf(table.getValueAt(jTable.getSelectedRow(), 2));
        String servingSize = String.valueOf(table.getValueAt(jTable.getSelectedRow(), 3));
        String calories = String.valueOf(table.getValueAt(jTable.getSelectedRow(), 4));
        String fat = String.valueOf(table.getValueAt(jTable.getSelectedRow(), 5));
        String cholesterol = String.valueOf(table.getValueAt(jTable.getSelectedRow(), 6));
        String sodium = String.valueOf(table.getValueAt(jTable.getSelectedRow(), 7));
        String carbs = String.valueOf(table.getValueAt(jTable.getSelectedRow(), 8));
        String fiber = String.valueOf(table.getValueAt(jTable.getSelectedRow(), 9));
        String protein = String.valueOf(table.getValueAt(jTable.getSelectedRow(), 10));
        
        // check values recieved from the mouse click event
        selectedIngredient = new Ingredient(Double.parseDouble(amount), name, Double.parseDouble(servingSize), Double.parseDouble(calories), Double.parseDouble(fat), Double.parseDouble(cholesterol), Double.parseDouble(sodium), Double.parseDouble(carbs), Double.parseDouble(fiber), Double.parseDouble(protein));
        System.out.println("MainWindow: jTableMouseClicked ::: " + selectedIngredient.toString() + "  measurment: " + selectedMeasurement);        
    }//GEN-LAST:event_jTableMouseClicked

    // DELETE THIS
    private void jBtnGetLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnGetLabelMouseClicked
    }//GEN-LAST:event_jBtnGetLabelMouseClicked

    // displays the recipe label with ingredient totals for printing
    private void jBtnGetLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGetLabelActionPerformed
        String nameMessage = "A name is required for this recipe: ";
        int servings = 0;
        double weight = 0;
        String cookTime = "";
        int cookTemp = 0;
        String directions = "";
        String rName = jtfRecipeName.getText();
        // get user input recipe values
        try {             
            rName = jtfRecipeName.getText();
            servings = intTest(jtfServings.getText());
            weight = doubleTest(jtfWeight.getText());
            cookTime = jtfCookTime.getText();
            cookTemp = intTest(jtfCookTemp.getText());
            directions = jtaDirections.getText();                        
        } catch (NumberFormatException e) {
            System.err.println("Input Error at Get-Label Action Performed button: " + e);
        }
     
        recipe = new Recipe(rName, servings, weight, cookTemp, cookTime, directions);
        // open an instance of the Print Label Window
        NutritionLabel nl = new NutritionLabel();
        nl.setVisible(true);
        nl.pack();
        nl.setLocationRelativeTo(null);
        nl.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        System.out.println("Btn: get Label: " + recipe.toString());
    }//GEN-LAST:event_jBtnGetLabelActionPerformed
    // DELETE - NOT USED
    private void jBtnAddIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddIngredientActionPerformed
    }//GEN-LAST:event_jBtnAddIngredientActionPerformed
    // Quit Button
    private void jBtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtnCloseActionPerformed

    // DELETE - NOT USED 
    private void jBtnAddIngredient1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAddIngredient1MouseClicked
    }//GEN-LAST:event_jBtnAddIngredient1MouseClicked
    // DELETE - NOT USED 
    private void jBtnAddIngredient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddIngredient1ActionPerformed
    }//GEN-LAST:event_jBtnAddIngredient1ActionPerformed
    // Use jTableMouseClicked event to get the selected Ingredient from table
    private void jBtnEditIngredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditIngredActionPerformed
        // move the selected Ingredient from table to the Nutrition Label
        // get values from Ingredient.txt file, NOT the calculated values from table
        iName.setText(selectedIngredient.getiName()); 
        iServingSize.setText(String.valueOf(selectedIngredient.getServingSize()));
        iAmtInRecipe.setText(String.valueOf(selectedIngredient.getIngredAmt()));
//        iCalories.setText(String.valueOf(selectedIngredient.getCalories()));
//        iFat.setText(String.valueOf(selectedIngredient.getFat()));
//        iSodium.setText(String.valueOf(selectedIngredient.getSodium()));
//        iCholesterol.setText(String.valueOf(selectedIngredient.getCholesterol()));
//        iCarbs.setText(String.valueOf(selectedIngredient.getCarbohydrates()));
//        iFiber.setText(String.valueOf(selectedIngredient.getFiber()));
//        iProtein.setText(String.valueOf(selectedIngredient.getProtein()));
        iMeasurement.setSelectedIndex(getComboMeasurementIndex(selectedMeasurement));
        
        // delete the ingredient from the table
        table.removeRow(jTable.getSelectedRow());
        
        // subtract the selected ingredient from the totals
        calorieRunningTotals -= selectedIngredient.getCalories();
        fatRunningTotals -= selectedIngredient.getFat();
        cholRunningTotals -= selectedIngredient.getCholesterol();
        sodiumRunningTotals -= selectedIngredient.getSodium();
        carbRunningTotals -= selectedIngredient.getCarbohydrates();
        fiberRunningTotals -= selectedIngredient.getFiber();
        proteinRunningTotals -= selectedIngredient.getProtein();
        
        // save new running totals to ingredient object
        ingredientRunningTotals = new Ingredient(calorieRunningTotals, fatRunningTotals, cholRunningTotals, sodiumRunningTotals, carbRunningTotals, fiberRunningTotals, proteinRunningTotals);

    }//GEN-LAST:event_jBtnEditIngredActionPerformed
    // Add Ingredient to Recipe: get values in label and add to table
    private void jButtonAddIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddIngredientActionPerformed
        String name = "";
        double servingSize = 0;
        double ingredAmt = 0; 
        double cal = 0;
        double fat = 0;
        double sodium = 0;
        double cholesterol = 0;
        double carbs = 0;
        double fiber = 0;
        double protein = 0;
        String measure = "";
        // get user entered data
        try {
            name = iName.getText();
            servingSize = doubleTest(iServingSize.getText());
            ingredAmt = doubleTest(iAmtInRecipe.getText()); 
            cal = doubleTest(iCalories.getText());
            fat = doubleTest(iFat.getText());
            cholesterol = doubleTest(iCholesterol.getText());
            sodium = doubleTest(iSodium.getText());
            carbs = doubleTest(iCarbs.getText());
            fiber = doubleTest(iFiber.getText());
            protein = doubleTest(iProtein.getText());
            measure = String.valueOf(iMeasurement.getSelectedItem());
        } catch (NumberFormatException e) {
            System.err.print("Input Error at AddActionPerformed button: " + e);
        }
        // save values entered to file 
        Ingredient ingredientToFile = new Ingredient(ingredAmt, name, servingSize, cal, fat, cholesterol, sodium, carbs, fiber, protein);
        System.out.println("Entered values: " + ingredientToFile.toString() + " measure: " + measure);
        try {
            FileManagement.saveIngredient(ingredientToFile);
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // Calculate the nutrient's total values and display them in the table
        double calorieTotal = Calculate.nutrientTotal(servingSize, cal, ingredAmt, measure);
        double fatTotal = nutrientTotal(servingSize, fat, ingredAmt, measure);
        double cholTotal = nutrientTotal(servingSize, cholesterol, ingredAmt, measure);
        double sodiumTotal = nutrientTotal(servingSize, sodium, ingredAmt, measure);
        double carbTotal = nutrientTotal(servingSize, carbs, ingredAmt, measure);
        double fiberTotal = nutrientTotal(servingSize, fiber, ingredAmt, measure);
        double proteinTotal = nutrientTotal(servingSize, protein, ingredAmt, measure);
        table.insertRow(table.getRowCount(), new Object[]{ingredAmt, measure, name, servingSize, calorieTotal, fatTotal, cholTotal, sodiumTotal, carbTotal, fiberTotal, proteinTotal});
        System.out.println("MainWindow Class:: Nutrient total: "); 
        
        // accumulate totals for final display label in NutritionLabel
        calorieRunningTotals += calorieTotal;
        fatRunningTotals += fatTotal;
        cholRunningTotals += cholTotal;
        sodiumRunningTotals += sodiumTotal;
        carbRunningTotals += carbTotal;
        fiberRunningTotals += fiberTotal;
        proteinRunningTotals += proteinTotal;        
        ingredientRunningTotals = new Ingredient(calorieRunningTotals, fatRunningTotals, cholRunningTotals, sodiumRunningTotals, carbRunningTotals, fiberRunningTotals, proteinRunningTotals);
        System.out.println("Ingredient running totals: " + ingredientRunningTotals.toString());         
        
        // clear data from Nutrition label
        iName.setText(""); 
        iServingSize.setText(String.valueOf(""));
        iAmtInRecipe.setText(String.valueOf(""));
        iCalories.setText(String.valueOf(""));
        iFat.setText(String.valueOf(""));
        iSodium.setText(String.valueOf(""));
        iCholesterol.setText(String.valueOf(""));
        iCarbs.setText(String.valueOf(""));
        iFiber.setText(String.valueOf(""));
        iProtein.setText(String.valueOf(""));
        iMeasurement.setSelectedIndex(0);        
    }//GEN-LAST:event_jButtonAddIngredientActionPerformed

    // delete the ingredient from the table and subtract the nutrient values    
    private void jButtonDeleteIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteIngredientActionPerformed
        // Use jTableMouseClicked event to get the selected Ingredient from table
        table.removeRow(jTable.getSelectedRow());
        
        // subtract the selected ingredient from the totals
        calorieRunningTotals -= selectedIngredient.getCalories();
        fatRunningTotals -= selectedIngredient.getFat();
        cholRunningTotals -= selectedIngredient.getCholesterol();
        sodiumRunningTotals -= selectedIngredient.getSodium();
        carbRunningTotals -= selectedIngredient.getCarbohydrates();
        fiberRunningTotals -= selectedIngredient.getFiber();
        proteinRunningTotals -= selectedIngredient.getProtein();
        
        // save new running totals to ingredient object
        ingredientRunningTotals = new Ingredient(calorieRunningTotals, fatRunningTotals, cholRunningTotals, sodiumRunningTotals, carbRunningTotals, fiberRunningTotals, proteinRunningTotals);        
    }//GEN-LAST:event_jButtonDeleteIngredientActionPerformed

    // test user input to see if valid type -- website for testing input:
    // http://moriel.smarterthanthat.com/tips/java/java-user-input-validation/
    public double doubleTest(String userInput) {
        try {
            if (userInput != null) {
                double d = Double.parseDouble(userInput);
                return d;
            } 
            else {
                return 0;
            }
        } catch(NumberFormatException e) {
            System.err.println("Input Error at doubleTest: " + e);
            return 0;
        }
    }
    
    // test user input to see if valid type 
    public int intTest(String userInput) {
        try {
            if (userInput != null) {
                int i = Integer.parseInt(userInput);
                return i;
            } 
            else {
                return 0;
            }
        } catch(NumberFormatException e) {
            System.err.println("Input Error at intTest button: " + e);
            return 0;
        }
    }
    
    // used in editing table rows. Gets the index value for combo box.
    private int getComboMeasurementIndex(String measurementType) {
        int comboIndexValue;
        switch (measurementType) {
            case "grams": 
                comboIndexValue = 0;
                break;
            case "liquid oz": 
                comboIndexValue = 1;
                break;
            case "dry oz":
                comboIndexValue = 2;
                break;    
            case "teaspoon":
                comboIndexValue = 3;
                break;
            case "tablespoon":
                comboIndexValue = 4;
                break;
            case "milligram":
                comboIndexValue = 5;
                break;
            case "liquid cup":
                comboIndexValue = 6;
                break;
            case "dry cup":
                comboIndexValue = 7;
                break;
            case "liquid pint":
                comboIndexValue = 8;
                break;
            case "dry pint":
                comboIndexValue = 9;
                break;
            default:
                comboIndexValue = 0;
                break;
        } 
        return comboIndexValue;
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });      
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField iAmtInRecipe;
    private javax.swing.JTextField iCalories;
    private javax.swing.JTextField iCarbs;
    private javax.swing.JTextField iCholesterol;
    private javax.swing.JTextField iFat;
    private javax.swing.JTextField iFiber;
    private javax.swing.JComboBox<String> iMeasurement;
    private javax.swing.JTextField iName;
    private javax.swing.JTextField iProtein;
    private javax.swing.JTextField iServingSize;
    private javax.swing.JTextField iSodium;
    private javax.swing.JButton jBtnAddIngredient;
    private javax.swing.JButton jBtnAddIngredient1;
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnCancel1;
    private javax.swing.JButton jBtnClose;
    private javax.swing.JButton jBtnEditIngred;
    private javax.swing.JButton jBtnGetLabel;
    private javax.swing.JButton jBtnResetAll;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAdd1;
    private javax.swing.JButton jButtonAddIngredient;
    private javax.swing.JButton jButtonDeleteIngredient;
    private javax.swing.JComboBox<String> jComboMeasurement;
    private javax.swing.JComboBox<String> jComboMeasurement1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelDirections;
    private javax.swing.JPanel jPanelIngredients;
    private javax.swing.JPanel jPanelRecipe;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea jtaDirections;
    private javax.swing.JTextField jtfAmtInrecipe;
    private javax.swing.JTextField jtfAmtInrecipe1;
    private javax.swing.JTextField jtfCalories;
    private javax.swing.JTextField jtfCalories1;
    private javax.swing.JTextField jtfCarbs;
    private javax.swing.JTextField jtfCarbs1;
    private javax.swing.JTextField jtfCholesterol;
    private javax.swing.JTextField jtfCholesterol1;
    private javax.swing.JTextField jtfCookTemp;
    private javax.swing.JTextField jtfCookTime;
    private javax.swing.JTextField jtfFat;
    private javax.swing.JTextField jtfFat1;
    private javax.swing.JTextField jtfFiber;
    private javax.swing.JTextField jtfFiber1;
    private javax.swing.JTextField jtfIngredientName;
    private javax.swing.JTextField jtfIngredientName1;
    private javax.swing.JTextField jtfProtein;
    private javax.swing.JTextField jtfProtein1;
    private javax.swing.JTextField jtfRecipeName;
    private javax.swing.JTextField jtfServingSizeLabel;
    private javax.swing.JTextField jtfServingSizeLabel1;
    private javax.swing.JTextField jtfServings;
    private javax.swing.JTextField jtfSodium;
    private javax.swing.JTextField jtfSodium1;
    private javax.swing.JTextField jtfWeight;
    // End of variables declaration//GEN-END:variables
}
